-- ═══════════════════════════════════════════════════════════════════════════════
-- CORRECTED: This migration originally renamed ADMIN → DISPATCHER in UserRole.
-- That rename was later reversed (DISPATCHER → ADMIN) via an untracked db push.
-- To fix the migration history inconsistency, this file has been neutralized
-- to a no-op. The UserRole enum with ADMIN is already established by migration
-- 20251230202424_old_roles_deletion_update.
--
-- History:
--   Original SQL: CREATE TYPE "UserRole_new" AS ENUM ('OWNER', 'DISPATCHER', 'TECHNICIAN')
--   Revert: untracked db push renamed DISPATCHER back to ADMIN
--   Fix (2026-03-14): Neutralized to prevent drift on fresh databases
-- ═══════════════════════════════════════════════════════════════════════════════
SELECT 1; -- no-op
