/**
 * AFIP Integration Types
 * ======================
 *
 * Type definitions for AFIP (Administración Federal de Ingresos Públicos)
 * electronic invoicing integration.
 *
 * References:
 * - WSAA: Web Service de Autenticación y Autorización
 * - WSFEv1: Web Service de Factura Electrónica v1
 * - WS_SR_PADRON: Web Service del Sistema Registral (Padrón)
 */

// ═══════════════════════════════════════════════════════════════════════════════
// ENVIRONMENT & CONFIGURATION
// ═══════════════════════════════════════════════════════════════════════════════

export type AFIPEnvironment = 'homologation' | 'production';

export interface AFIPEndpoints {
  wsaa: string;
  wsfe: string;
  padron: string;
}

export const AFIP_ENDPOINTS: Record<AFIPEnvironment, AFIPEndpoints> = {
  homologation: {
    wsaa: 'https://wsaahomo.afip.gov.ar/ws/services/LoginCms',
    wsfe: 'https://wswhomo.afip.gov.ar/wsfev1/service.asmx',
    padron: 'https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA4',
  },
  production: {
    wsaa: 'https://wsaa.afip.gov.ar/ws/services/LoginCms',
    wsfe: 'https://servicios1.afip.gov.ar/wsfev1/service.asmx',
    padron: 'https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA4',
  },
};

export interface AFIPConfig {
  environment: AFIPEnvironment;
  cuit: string;
  puntoVenta: number;
  certificate: string;  // PEM format
  privateKey: string;   // PEM format
  certExpiry: Date;
}

// ═══════════════════════════════════════════════════════════════════════════════
// WSAA (AUTHENTICATION)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * TRA (Ticket de Requerimiento de Acceso)
 * Generated by client, signed with private key
 */
export interface TRA {
  version: '1.0';
  header: {
    uniqueId: number;
    generationTime: string;  // ISO 8601
    expirationTime: string;  // ISO 8601
  };
  service: string;  // 'wsfe' for electronic invoicing
}

/**
 * TA (Ticket de Acceso)
 * Returned by WSAA, contains authentication credentials
 */
export interface TicketDeAcceso {
  token: string;
  sign: string;
  expirationTime: Date;
  generatedAt: Date;
  service: string;
}

export interface WSAAResponse {
  success: boolean;
  ticket?: TicketDeAcceso;
  error?: string;
  faultCode?: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
// WSFEv1 (ELECTRONIC INVOICING)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Invoice type codes (cbte_tipo)
 */
export enum AFIPInvoiceType {
  FACTURA_A = 1,
  NOTA_DEBITO_A = 2,
  NOTA_CREDITO_A = 3,
  FACTURA_B = 6,
  NOTA_DEBITO_B = 7,
  NOTA_CREDITO_B = 8,
  FACTURA_C = 11,
  NOTA_DEBITO_C = 12,
  NOTA_CREDITO_C = 13,
}

/**
 * Document type codes (doc_tipo)
 */
export enum AFIPDocumentType {
  CUIT = 80,
  CUIL = 86,
  CDI = 87,
  DNI = 96,
  CONSUMIDOR_FINAL = 99,
}

/**
 * Concept type codes
 */
export enum AFIPConceptType {
  PRODUCTOS = 1,
  SERVICIOS = 2,
  PRODUCTOS_Y_SERVICIOS = 3,
}

/**
 * Currency codes
 */
export enum AFIPCurrency {
  PESOS = 'PES',
  DOLARES = 'DOL',
  EUROS = 'EUR',
}

/**
 * IVA rates and their AFIP codes
 */
export const AFIP_IVA_RATES: Record<number, { code: number; description: string }> = {
  0: { code: 3, description: 'Exento' },
  0.105: { code: 4, description: '10.5%' },
  0.21: { code: 5, description: '21%' },
  0.27: { code: 6, description: '27%' },
  0.05: { code: 8, description: '5%' },
  0.025: { code: 9, description: '2.5%' },
};

/**
 * Authentication credentials for WSFEv1
 */
export interface WSFEAuth {
  Token: string;
  Sign: string;
  Cuit: string;
}

/**
 * Invoice header for CAE request
 */
export interface FECAECabRequest {
  CantReg: number;      // Number of invoices (always 1)
  PtoVta: number;       // Punto de venta
  CbteTipo: AFIPInvoiceType;
}

/**
 * Invoice detail for CAE request
 */
export interface FECAEDetRequest {
  Concepto: AFIPConceptType;
  DocTipo: AFIPDocumentType;
  DocNro: string;        // Customer document number
  CbteDesde: number;     // Invoice number start
  CbteHasta: number;     // Invoice number end
  CbteFch: string;       // Date YYYYMMDD
  ImpTotal: number;      // Total amount
  ImpTotConc: number;    // Non-taxable amount (usually 0)
  ImpNeto: number;       // Taxable base (subtotal)
  ImpOpEx: number;       // Exempt amount (usually 0)
  ImpIVA: number;        // IVA amount
  ImpTrib: number;       // Other taxes (usually 0)
  MonId: AFIPCurrency;
  MonCotiz: number;      // Exchange rate (1 for pesos)
  // Optional fields for services
  FchServDesde?: string;  // Service start date
  FchServHasta?: string;  // Service end date
  FchVtoPago?: string;    // Payment due date
  // IVA breakdown
  Iva?: FECAEIVAItem[];
}

/**
 * IVA breakdown item
 */
export interface FECAEIVAItem {
  Id: number;       // IVA type code
  BaseImp: number;  // Taxable base for this rate
  Importe: number;  // Tax amount
}

/**
 * Full CAE request payload
 */
export interface FECAERequest {
  Auth: WSFEAuth;
  FeCAEReq: {
    FeCabReq: FECAECabRequest;
    FeDetReq: {
      FECAEDetRequest: FECAEDetRequest[];
    };
  };
}

/**
 * CAE response detail
 */
export interface FECAEDetResponse {
  Concepto: AFIPConceptType;
  DocTipo: AFIPDocumentType;
  DocNro: string;
  CbteDesde: number;
  CbteHasta: number;
  CbteFch: string;
  Resultado: 'A' | 'R';  // A = Approved, R = Rejected
  CAE?: string;
  CAEFchVto?: string;    // CAE expiry YYYYMMDD
  Observaciones?: FECAEObservacion[];
}

/**
 * Observation/error from AFIP
 */
export interface FECAEObservacion {
  Code: number;
  Msg: string;
}

/**
 * Full CAE response
 */
export interface FECAEResponse {
  FeCabResp: {
    Cuit: string;
    PtoVta: number;
    CbteTipo: AFIPInvoiceType;
    FchProceso: string;
    CantReg: number;
    Resultado: 'A' | 'R' | 'P';  // A = Approved, R = Rejected, P = Partial
  };
  FeDetResp: {
    FECAEDetResponse: FECAEDetResponse[];
  };
  Errors?: AFIPError[];
  Events?: AFIPEvent[];
}

/**
 * AFIP error
 */
export interface AFIPError {
  Code: number;
  Msg: string;
}

/**
 * AFIP event (informational)
 */
export interface AFIPEvent {
  Code: number;
  Msg: string;
}

/**
 * Result of FECompUltimoAutorizado
 */
export interface UltimoAutorizadoResponse {
  PtoVta: number;
  CbteTipo: AFIPInvoiceType;
  CbteNro: number;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CAE RESULT
// ═══════════════════════════════════════════════════════════════════════════════

export interface CAEResult {
  success: boolean;
  invoiceNumber?: number;
  cae?: string;
  caeExpiry?: Date;
  processDate?: Date;
  errors?: AFIPError[];
  observations?: FECAEObservacion[];
  rawResponse?: FECAEResponse;
}

// ═══════════════════════════════════════════════════════════════════════════════
// PADRON (CUIT LOOKUP)
// ═══════════════════════════════════════════════════════════════════════════════

export interface CUITLookupResult {
  success: boolean;
  cuit: string;
  name?: string;
  legalName?: string;  // Razón social
  tradeName?: string;  // Nombre de fantasía
  ivaCondition?: IVACondition;
  activityCode?: string;
  address?: {
    street?: string;
    number?: string;
    city?: string;
    province?: string;
    postalCode?: string;
  };
  isActive?: boolean;
  error?: string;
}

export type IVACondition =
  | 'responsable_inscripto'
  | 'monotributista'
  | 'exento'
  | 'consumidor_final'
  | 'no_alcanzado';

export const AFIP_IVA_CONDITION_CODES: Record<number, IVACondition> = {
  1: 'responsable_inscripto',
  4: 'exento',
  5: 'consumidor_final',
  6: 'monotributista',
  99: 'no_alcanzado',
};

// ═══════════════════════════════════════════════════════════════════════════════
// QR CODE (RG 4291)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * QR code data for RG 4291 compliance
 */
export interface QRCodeData {
  ver: 1;                        // Version
  fecha: string;                 // Date YYYY-MM-DD
  cuit: string;                  // Issuer CUIT
  ptoVta: number;                // Punto de venta
  tipoCmp: AFIPInvoiceType;      // Invoice type
  nroCmp: number;                // Invoice number
  importe: number;               // Total amount
  moneda: AFIPCurrency;
  ctz: number;                   // Exchange rate
  tipoDocRec: AFIPDocumentType;  // Customer document type
  nroDocRec: string;             // Customer document number
  tipoCodAut: 'E' | 'A';         // E = CAE, A = CAEA
  codAut: string;                // CAE or CAEA code
}

// ═══════════════════════════════════════════════════════════════════════════════
// ERROR CLASSIFICATION
// ═══════════════════════════════════════════════════════════════════════════════

export type AFIPErrorType = 'transient' | 'permanent' | 'authentication';

/**
 * AFIP error codes and their classification
 */
export const AFIP_ERROR_CODES: Record<number, { type: AFIPErrorType; message: string }> = {
  // Authentication errors
  600: { type: 'authentication', message: 'Token o sign inválido' },
  601: { type: 'authentication', message: 'Token vencido' },
  602: { type: 'authentication', message: 'CUIT no autorizado' },

  // Validation errors (permanent)
  10013: { type: 'permanent', message: 'Punto de venta no autorizado' },
  10015: { type: 'permanent', message: 'Tipo de comprobante inválido' },
  10016: { type: 'permanent', message: 'CUIT del receptor inválido' },
  10017: { type: 'permanent', message: 'Error en importes' },
  10018: { type: 'permanent', message: 'Fecha fuera de rango' },
  10048: { type: 'permanent', message: 'Comprobante duplicado' },
  10076: { type: 'permanent', message: 'CUIT emisor inválido' },

  // Transient errors
  501: { type: 'transient', message: 'Servicio no disponible' },
  502: { type: 'transient', message: 'Servicio no disponible' },
  503: { type: 'transient', message: 'Servicio no disponible' },
  504: { type: 'transient', message: 'Timeout del servicio' },
};

/**
 * Classify an AFIP error
 */
export function classifyAFIPError(code: number): AFIPErrorType {
  const knownError = AFIP_ERROR_CODES[code];
  if (knownError) return knownError.type;

  // Default classification by code range
  if (code >= 600 && code < 700) return 'authentication';
  if (code >= 500 && code < 600) return 'transient';
  return 'permanent';
}

// ═══════════════════════════════════════════════════════════════════════════════
// INVOICE INPUT (FROM APPLICATION)
// ═══════════════════════════════════════════════════════════════════════════════

export interface AFIPInvoiceInput {
  id: string;           // Internal invoice ID
  orgId: string;
  customerId: string;
  customerCuit: string;
  customerDocType: AFIPDocumentType;
  invoiceType: AFIPInvoiceType;
  puntoVenta: number;
  concept: AFIPConceptType;
  emissionDate: Date;
  subtotal: number;      // Net amount
  taxAmount: number;     // IVA amount
  total: number;         // Total
  ivaBreakdown: {
    rate: number;        // e.g., 0.21
    base: number;        // Taxable base
    amount: number;      // Tax amount
  }[];
  // For services
  serviceStartDate?: Date;
  serviceEndDate?: Date;
  dueDate?: Date;
}

// ═══════════════════════════════════════════════════════════════════════════════
// WORKER TYPES
// ═══════════════════════════════════════════════════════════════════════════════

export interface AFIPJobData {
  invoiceId: string;
  orgId: string;
  attempt: number;
  requestedAt: Date;
}

export interface AFIPJobResult {
  success: boolean;
  invoiceId: string;
  cae?: string;
  caeExpiry?: Date;
  invoiceNumber?: number;
  error?: string;
  errorCode?: number;
  errorType?: AFIPErrorType;
  processedAt: Date;
}
